In [ ]:
#1

import numpy as np
a=np.arange(1,6)
b=a.copy()
b[0]=32
print(a)
print(b)


[1 2 3 4 5]
[32  2  3  4  5]


In [ ]:
#2

import numpy as np
a=np.arange(6,10)
b=a.view()
b[0]=3
print(a)
print(b)

[3 7 8 9]
[3 7 8 9]


In [ ]:
#3

import numpy as np
arr=np.arange(1,6)
b=a.copy()
arr[0]=32
print(b.base,"\n")
c=np.arange(6,10)
d=c.view()
c[0]=3
print(d.base)
# copy yil original n chnge varilla
# view yil orginal change akum
#  if we use a.base method  if the array is copy it will show (none) if it is view it will show the data

None 

[3 7 8 9]


In [ ]:
#4
import numpy as np
a=np.arange(1,5).reshape((2,2))
b=a[0].view()
b[0]=3
print(a,"\n")
print(b)


[[3 2]
 [3 4]] 

[3 2]


In [ ]:
#5
import numpy as np
a=np.arange(1,5).reshape((2,2))
b=a[0,:]
print(b,"\n")
print(b.base)
print("its view")

[1 2] 

[1 2 3 4]
its view


In [ ]:
#6
a=np.arange(1,5).reshape((2,2))
b=a.view()
np.may_share_memory(a,b)# true anel view allel false

True

In [ ]:
#7
import numpy as np
a=np.arange(1,7)
b=a.reshape(-1,2)
print(a,"\n")
print(b,"\n")
print(a.base)
print("its a view ")
print(np.shares_memory(a,b))# another method to check its view or copy

[1 2 3 4 5 6] 

[[1 2]
 [3 4]
 [5 6]] 

None
its a view 
True


In [ ]:
#8
a=np.arange(1,7)
print(a.shape,"\n")
b=a.reshape((-1,2))
print(b.shape)

(6,) 

(3, 2)


In [ ]:
#9
import numpy as np
a=np.arange(1,13)
b=a.reshape((3,-1))
c=b.reshape(1,3,-1)
print(b,"\n")
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
# 10
a=np.arange(1,13).reshape((3,4))
b=a.reshape((2,6))
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# 11
import numpy as np
a=np.arange(1,7).reshape((2,-1))
b=a.reshape((1,2,-1))
c=b.reshape(2,-1)
print(a,"\n")
print(b,"\n")
print(c)

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]] 

[[1 2 3]
 [4 5 6]]


In [ ]:
# 12
import numpy as np
a=np.arange(1,17).reshape((4,4))
b=a.reshape((2,8))
c=b.reshape(4,4)
print(a,"\n")
print(b,"\n")
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# 13
a=np.arange(1,7).reshape((1,-1,2))
print(a,"\n")
b=a.reshape(-1)
print(b)

[[[1 2]
  [3 4]
  [5 6]]] 

[1 2 3 4 5 6]


In [ ]:
# 14
import numpy as np
a=np.arange(1,10).reshape((3,3))
print(a,"\n")
for row in a:
  print("row",row)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

row [1 2 3]
row [4 5 6]
row [7 8 9]


In [ ]:
# 15
import numpy as np
a=np.arange(1,7).reshape((2,3))
for i,x in np.ndenumerate(a):
  print(i,x)



(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
# 16
import numpy as np
a=np.arange(8).reshape((2,-1,2))
for i,x in np.ndenumerate(a):
  print(i,x)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


In [ ]:
# 17
import numpy as np
a=np.arange(1,5).reshape((2,2))
for i in np.nditer(a):
  print(i)

1
2
3
4


In [ ]:
# 18
import numpy as np
a=np.arange(8).reshape((2,-1,2))
for i,x in np.ndenumerate(a):
  print(i,x)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


In [ ]:
# 19
import numpy as np
a=np.array([1,2,3,4],ndmin=6)
for i in np.nditer(a):
  print(i)

1
2
3
4


In [ ]:
# 20
import numpy as np
a=np.arange(1,5).reshape((2,2))
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)


1.0
2.0
3.0
4.0


In [ ]:
# 21
import numpy as np
a=np.array([1,2.5,3,4])
for i in np.nditer(a):
  print(i)

1.0
2.5
3.0
4.0


In [ ]:
# 22
import numpy as np
a=np.arange(1,5).reshape((2,2))
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)
#  if we use op_dtypes=[] it will change to another datatype

1.0
2.0
3.0
4.0


In [ ]:
# 23
import numpy as np
a=np.arange(1,11)
for i in np.nditer(a[::2]):
  print(i)

1
3
5
7
9


In [ ]:
# 24
import numpy as np
a=np.array([[1,2],[3,4],[5,6],[7,8]])
for i in np.ndenumerate(a[::,1:]):
  print(i)

((0, 0), 2)
((1, 0), 4)
((2, 0), 6)
((3, 0), 8)


In [ ]:
# 25
import numpy as np
c=np.arange(1,7).reshape((1,-1,2))
print(a,"\n")

for g in np.ndenumerate(c[:,:,1:]):
  print(g)

[[[1 2]
  [3 4]
  [5 6]]] 

((0, 0, 0), 2)
((0, 1, 0), 4)
((0, 2, 0), 6)
